import Image from 'next/image';
import styles from '../styles/Home.module.css';


export default function AboutUs() {
return (
        <>
           <title>About Us</title>
               <meta name="description" content="Generated by create next app" />
               <meta charSet="UTF-8"/>
               <meta name="viewport" content="width=device-width, initial-scale=1" />
               <link rel="stylesheet" href="https://rsms.me/inter/inter.css"/>
               <link rel="icon" href="/Picture1.png" />
      
              <header className={styles.navbar}>
              <div>
                  <Image className={styles.logo}
                    src="/Picture1.png"
                    alt="Logo"
                    width={100}
                    height={100}
                    priority
                  />
                </div>
                <header className={styles.centerbefore}>
            
                <a href=" / "> <button>Home</button></a>
                <a href="about"> <button>About Us</button></a>
                <a href="photos"> <button>Gallery</button></a>
                <a href="contact"> <button>Contact Us</button></a>
                </header>

                </header>
                   
           <main className={styles.main}>
               <a href="">
                <div>
                   <h2> Who we are and what we do?</h2>
                   <p>
                       DNH was established in 2021 by two plant enthusiasts Naomi (BSc Hons Plant Health Ecology) and Beaulah. </p>

                   <p>
                       We started this exciting business because we saw a potential for a medicinal plant business while we were collecting a wide variety of medicinal plants to grow in our garden as a hobby. We first hosted a few formal information sessions to introduce these wonder plants and their ways of working to the public.</p>
                   Later on we started a plant nursery where we propagate some of these medicinal plants and make it available to the public to buy.

                   <p>
                       We are currently busy with the design of herbal products such as supplements, herbal teas and herbal extracts.
                       In the future, we plan on selling seed of some of the medicinal plants and heirloom seed of some vegetables.

                   </p>
                   </div>
                   <div className={styles.center}>
                       <Image
                           className={styles.logo}
                           src="/graaf.jpg"
                           alt="Gardening"
                           width={400}
                           height={300}
                           priority />
                   </div>

                  
                    <div>
                   <h3> Medicinal Plants Background</h3>
                   <p>
                       Today, humanity is turning back to nature to alleviate and prevent disease. Indeed, our ancestors made use of natural medicines such as buchu and african wormwood in a time without a lot of doctors, when they moved inland.</p>
                   <p>
                       As modern humans, we have already lost that knowledge. If one has the knowledge to use the herbs correctly, it is very satisfying, because there are no real side effects and it is always at hand. In other countries, people return to natural medicine and process their herbs each season into oils, salves, tinctures and dried herbs so that they can use them all year round.</p>

                   <p>
                       If you decide to go the satisfying route of growing your own medicinal herbs, we suggest you start with three or five herbs and learn all you can about those herbs.
                   </p>
                   </div>

                   <div className={styles.center}>
                       <Image
                           className={styles.logo}
                           src="/kas.jpg"
                           alt="Herbs"
                           width={400}
                           height={300}
                           priority />
                   </div>


                   <div 
                   className={styles.center}>

                       <Image
                           className={styles.logo}
                           src="/precaution1.png"
                           alt="Precautions"
                           width={400}
                           height={400}
                           priority />
                   </div>

                   <div>
                   <footer className={styles.footer}>
                       <pre> © 2023 DNH WebApp - A Project Built with Next.js                                                                                                 demonstratenatureshealing@gmail.com</pre>
                   </footer>
                   </div>
        </a>
    </main>
    </>
   );
};