import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function ContactUs() {
return (
        <>
           <title>Contact Us</title>
               <meta name="description" content="Generated by create next app" />
               <meta charSet="UTF-8"/>
               <meta name="viewport" content="width=device-width, initial-scale=1" />
               <link rel="stylesheet" href="https://rsms.me/inter/inter.css"/>
               <link rel="icon" href="/Picture1.png" />
      
              <header className={styles.navbar}>
              <div>
                  <Image className={styles.logo}
                    src="/Picture1.png"
                    alt="Logo"
                    width={100}
                    height={100}
                    priority
                  />
                </div>
                </header>
                <header className={styles.centerbefore}>
            
                <a href=" / "> <button>Home</button></a>
                <a href="about"> <button>About Us</button></a>
                <a href="photos"> <button>Gallery</button></a>
                <a href="contact"> <button>Contact Us</button></a>
                </header>
                
                <div className={styles.centerbefore}>
                       <h1>
                                Contact Us
                       </h1>

        
                       <Image className={styles.center}
                           src="/baba.jpg"
                           alt="Gardening"
                           width={800}
                           height={700}
                           priority 
                           />
                           
                       <h3>Next time you are thinking about gardening, give us a call:</h3>

                        <button><h2>074 438 0907</h2></button>


                       <h3>Or send us an email:</h3>

                         <button><h2>demonstratenatureshealing@gmail.com</h2></button>
                       
                  

                   
                       <pre>
                    <h1>Business Hours </h1>

                     <box><h2>Sundays to Thursdays: 10:00 - 17:00</h2>

                       <h3> Fridays, Saturdays and Public Holidays: CLOSED</h3></box>
                       </pre>
                   </div>
                   

                    <div>
                   <footer className={styles.footer}>
                       <pre> © 2023 DNH WebApp - A Project Built with Next.js                                                                                                 demonstratenatureshealing@gmail.com</pre>
                   </footer>
                   </div>
    </>
   );
};
