import Image from 'next/image';
import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() { 
return (
  <>
    <Head>
     <title>DNH Home</title>
         <meta name="description" content="Generated by create next app" />
         <meta charSet="UTF-8"/>
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/Picture1.png" />
       </Head>

       
       <header className={styles.center}>
              <div>
                  <Image 
              src="/Picture1.png"
              alt="Logo"
              width={200}
              height={200}
              priority
            />
           </div>
            </header>

          <body className={styles.center}>
            <a
            href="/about"
            className={styles.card}
            target="_blank"
            rel=""
          >
            <h2 className={inter.className}>
              Learn more about us <span>-&gt;</span>
            </h2>
            <div className={inter.className}>
              Find out who we are and what exactly we do.
            </div>
          </a>

          <a
            href="/photos"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Gallery <span>-&gt;</span>
            </h2>
            <div className={inter.className}>
              Visualise the beauty of Medicinal plants.
            </div>
          </a>

            <a
            href="/contact"
            className={styles.card}
            target="_blank"
            rel=""
          >
            <h2 className={inter.className}>
              Contact Us <span>-&gt;</span>
            </h2>
            <div className={inter.className}>
              Find our contact details.
            </div>
          </a>
          </body>
          
      <div>
                   <footer className={styles.footer}>
                       <pre> © 2023 DNH WebApp - A Project Built with Next.js                                                                                                 demonstratenatureshealing@gmail.com</pre>
                   </footer>
                   </div>
    </>
   );
};