import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';


export default function Gallery() {
   return (
    <div className={styles.container}>

        <title>DNH Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Picture1.png" />
  
      
              <header className={styles.navbar}>
              <div>
                  <Image className={styles.logo}
                    src="/Picture1.png"
                    alt="Logo"
                    width={100}
                    height={100}
                    priority
                  />
                </div>
                <header className={styles.centerbefore}>
            
            <a href=" / "> <button>Home</button></a>
            <a href="about"> <button>About Us</button></a>
            <a href="photos"> <button>Gallery</button></a>
            <a href="contact"> <button>Contact Us</button></a>
            </header>
                </header>
        
        <main className={styles.main}>
          <a href=""> 
            <h2> Moments Captured Of Our Beautiful Plants</h2>

            <Image
            src="/Elderberry.jpg"
            alt="Elderberry"
            width={400}
            height={300}
            />
            
            <Image
            src="/Aloevera.jpg"
            alt="Aloe vera"
            width={400}
            height={300}
            />
            
            <Image
            src="/ArtemesiaA.png"
            alt="African Wormwood (Artemesia afra)"
            width={400}
            height={300}
            />
            
            <Image
            src="/ArtemesiaAB.jpg"
            alt="Common Wormwood (Artemesia absinthium)"
            width={400}
            height={300}
            />
            
            <Image
            src="/Ashwagandha.jpg"
            alt="Ashwagandha"
            width={400}
            height={300}
            />

            <Image
            src="/chamomile.jpg"
            alt="Chamomile"
            width={400}
            height={300}
            />
            
            <Image
            src="/Comfrey.jpg"
            alt="Comfrey"
            width={400}
            height={300}
            />
            
            <Image
            src="/Gojibessie.jpg"
            alt="Goji berry"
            width={400}
            height={300}
            />
            
            <Image
            src="/Kankerbos.jpg"
            alt="Cancerbush (Lessertia frutescens) "
            width={400}
            height={300}
            />

            <Image
            src="/Kappertjies.jpg"
            alt="Capers "
            width={400}
            height={300}
            />
            
            <Image
            src="/Katjiedrieblaar.jpg"
            alt="Katjie Drieblaar "
            width={400}
            height={300}
            />
            
            <Image
            src="/Kougoed.jpg"
            alt="Sceletium tortuosum"
            width={400}
            height={300}
            />
            
            <Image
            src="/lemonbalm.jpg"
            alt="Lemon Balm (Melissa officinalis) "
            width={400}
            height={300}
            />
            
            <Image
            src="/Marshmellow.jpg"
            alt="Marshmellow "
            width={400}
            height={300}
            />
            
            <Image
            src="/Mullein.jpg"
            alt="Mullein "
            width={400}
            height={300}
            />
           
            <Image
            src="/Ocimum gratissimumTulsi.jpg"
            alt="Tulsi Vana (Holy Basil)"
            width={400}
            height={300}
            />
            
            <Image
            src="/Pelargonium.jpg"
            alt="Rose-mint scented Pelargonium "
            width={400}
            height={300}
            />
            
            <Image
            src="/PelargoniumSid.png"
            alt="Pelargonium sidoides"
            width={400}
            height={300}
            />
            
            <Image
            src="/Plantagomajor.png"
            alt="Broadleaf plantain "
            width={400}
            height={300}
            />
           
            <Image
            src="/Redclover.jpg"
            alt="Red Clover "
            width={400}
            height={300}
            />
            
            <Image
            src="/Scullcap.jpg"
            alt="Skullcap"
            width={400}
            height={300}
            />

            <Image
            src="/Wynruit.jpg"
            alt="Rue"
            width={400}
            height={300}
            />


<div>
                   <footer className={styles.footer}>
                       <pre> © 2023 DNH WebApp - A Project Built with Next.js                                                                                                 demonstratenatureshealing@gmail.com</pre>
                   </footer>
                   </div>
      </a>
      </main>
    </div>
   );
}